name: Build for macOS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://stackoverflow.com/a/72408109/6942800
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Least-privilege: only needs to read code for building.
permissions:
  contents: read

jobs:
  build:
    name: Build Boring Notch (${{ matrix.xcode }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            xcode: "^16"
          - os: macos-26
            xcode: "^26"
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build
        uses: mxcl/xcodebuild@e366f14791346edb74397fe9a762ccee86eddc06 # v3.5.0
        with:
          xcode: ${{ matrix.xcode }}
          platform: macOS
          scheme: boringNotch
          action: build
          verbosity: xcpretty
          upload-logs: always
          configuration: release
