name: Build for macOS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://stackoverflow.com/a/72408109/6942800
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Least-privilege: only needs to read code for building.
permissions:
  contents: read

jobs:
  build:
    name: Build Boring Notch
    strategy:
      matrix:
        platform:
          - macOS
        xcode:
          - ^16
        scheme:
          - boringNotch
    runs-on: macos-latest
    steps:
    - name: Code Checkout
      # TODO: pin to immutable SHA
      uses: actions/checkout@v5
    - # TODO: pin to immutable SHA
      uses: mxcl/xcodebuild@v3
      with:
        xcode: ${{ matrix.xcode }}
        platform: ${{ matrix.platform }}
        scheme: ${{ matrix.scheme }}
        action: build
        verbosity: xcpretty
        upload-logs: always
        configuration: release
